import { useOpshubStore } from '@/lib/store/opshub-store'
import type {
    ActivityEntry,
    AIAgentRecommendation,
    ChangelogEntry,
    ChecklistStep,
    DetectedAnomaly,
    DiscussionComment,
    ExecutionChecklist,
    Factory,
    OpshubPost,
    TeamMember,
    WorkflowRepo,
    WorkOrderCard,
    WorkOrderTask,
} from '@/lib/types/opshub'
import { useEffect, useMemo } from 'react'

// ─── Mock Team ──────────────────────────────────────────────────
export const MOCK_TEAM: TeamMember[] = [
    { id: 'sarah-chen', name: 'Sarah Chen', role: 'Plant Manager', facility: 'Munich Plant', avatarInitials: 'SC', avatarColor: '#3B82F6', status: 'available' },
    { id: 'omar-khalid', name: 'Omar Khalid', role: 'Reliability Engineer', facility: 'Munich Plant', avatarInitials: 'OK', avatarColor: '#10B981', status: 'available' },
    { id: 'ahmed-nasser', name: 'Ahmed Nasser', role: 'Maintenance Lead', facility: 'Munich Plant', avatarInitials: 'AN', avatarColor: '#EF4444', status: 'available' },
    { id: 'lisa-park', name: 'Lisa Park', role: 'Reliability Engineer', facility: 'Munich Plant', avatarInitials: 'LP', avatarColor: '#EC4899', status: 'in-field' },
    { id: 'fahad-alrashid', name: 'Fahad Al-Rashid', role: 'Plant Manager', facility: 'Riyadh Manufacturing', avatarInitials: 'FA', avatarColor: '#8B5CF6', status: 'available' },
    { id: 'ai-agent', name: 'AI Agent', role: 'System', facility: 'Munich Plant', avatarInitials: '🤖', avatarColor: '#A855F7', status: 'available', isAI: true },
]

// ─── Mock Factories ──────────────────────────────────────────────
const MOCK_FACTORIES: Factory[] = [
    {
        id: 'factory-munich',
        name: 'munich',
        displayName: 'Munich Plant',
        location: 'Germany',
        avatar: '🏭',
        metrics: { efficiency: 94.2, uptime: 99.1, activeWorkflows: 23, resolvedAnomalies: 156 },
    },
    {
        id: 'factory-shanghai',
        name: 'shanghai',
        displayName: 'Shanghai Facility',
        location: 'China',
        avatar: '🏗️',
        metrics: { efficiency: 91.8, uptime: 98.5, activeWorkflows: 31, resolvedAnomalies: 203 },
    },
    {
        id: 'factory-detroit',
        name: 'detroit',
        displayName: 'Detroit Assembly',
        location: 'USA',
        avatar: '🔧',
        metrics: { efficiency: 89.5, uptime: 97.2, activeWorkflows: 18, resolvedAnomalies: 89 },
    },
    {
        id: 'factory-tokyo',
        name: 'tokyo',
        displayName: 'Tokyo Innovation Lab',
        location: 'Japan',
        avatar: '⚡',
        metrics: { efficiency: 96.1, uptime: 99.7, activeWorkflows: 42, resolvedAnomalies: 312 },
    },
    {
        id: 'factory-saopaulo',
        name: 'saopaulo',
        displayName: 'São Paulo Hub',
        location: 'Brazil',
        avatar: '🌿',
        metrics: { efficiency: 88.3, uptime: 96.8, activeWorkflows: 15, resolvedAnomalies: 67 },
    },
    {
        id: 'factory-riyadh',
        name: 'riyadh',
        displayName: 'Riyadh Manufacturing',
        location: 'Saudi Arabia',
        avatar: '🏗️',
        metrics: { efficiency: 90.5, uptime: 98.2, activeWorkflows: 12, resolvedAnomalies: 34 },
    },
]

// ─── Mock Workflow Repos ─────────────────────────────────────────
const MOCK_REPOS: WorkflowRepo[] = [
    { id: 'repo-1', factoryId: 'factory-munich', name: 'Motor Vibration Protocol', description: 'Standard procedure for motor vibration monitoring and predictive maintenance triggering', stars: 4, forks: 2, isPublic: true, tags: ['motors', 'predictive', 'SOP-M-012'], language: 'Motors', lastUpdated: '2026-02-08T10:30:00Z', createdAt: '2025-11-15T08:00:00Z' },
    { id: 'repo-2', factoryId: 'factory-munich', name: 'HVAC Energy Savings Routine', description: 'AI-driven HVAC scheduling that reduced energy consumption 30% in Q4 2025', stars: 5, forks: 3, isPublic: true, tags: ['hvac', 'energy', 'SOP-E-007'], language: 'HVAC', lastUpdated: '2026-02-07T14:20:00Z', createdAt: '2025-09-22T09:00:00Z' },
    { id: 'repo-3', factoryId: 'factory-munich', name: 'Bearing Failure Early Warning', description: 'ML-based bearing degradation detection with 72h advance notice and automatic work order creation', stars: 5, forks: 4, isPublic: true, tags: ['bearings', 'predictive', 'SOP-M-047'], language: 'Motors', lastUpdated: '2026-02-05T16:45:00Z', createdAt: '2025-06-10T11:00:00Z' },
    { id: 'repo-4', factoryId: 'factory-shanghai', name: 'Assembly Line Balancing', description: 'Real-time workload distribution across stations to minimize bottlenecks', stars: 3, forks: 1, isPublic: true, tags: ['assembly', 'automation', 'SOP-A-003'], language: 'Assembly', lastUpdated: '2026-02-09T08:15:00Z', createdAt: '2025-08-01T07:00:00Z' },
    { id: 'repo-5', factoryId: 'factory-shanghai', name: 'Visual Quality Inspection', description: 'Computer vision defect detection integrated with MES for automatic rejection logging', stars: 5, forks: 4, isPublic: true, tags: ['quality', 'vision', 'SOP-Q-015'], language: 'Quality', lastUpdated: '2026-02-08T11:30:00Z', createdAt: '2025-04-15T10:00:00Z' },
    { id: 'repo-6', factoryId: 'factory-shanghai', name: 'Robot Arm Calibration Check', description: 'Automated calibration verification for KUKA robot arms with drift compensation', stars: 3, forks: 1, isPublic: true, tags: ['robotics', 'kuka', 'SOP-R-022'], language: 'Robotics', lastUpdated: '2026-02-06T09:00:00Z', createdAt: '2025-10-20T14:00:00Z' },
    { id: 'repo-7', factoryId: 'factory-detroit', name: 'Paint Booth Temperature Control', description: 'Automated temperature regulation for optimal coating adhesion and drying', stars: 2, forks: 0, isPublic: true, tags: ['paint', 'temperature', 'SOP-P-008'], language: 'Paint', lastUpdated: '2026-02-04T13:00:00Z', createdAt: '2025-12-01T08:00:00Z' },
    { id: 'repo-8', factoryId: 'factory-detroit', name: 'Weld Quality Monitoring', description: 'Real-time weld quality analysis with acoustic sensors and automatic parameter adjustment', stars: 4, forks: 2, isPublic: true, tags: ['welding', 'quality', 'SOP-W-011'], language: 'Welding', lastUpdated: '2026-02-07T15:30:00Z', createdAt: '2025-07-18T12:00:00Z' },
    { id: 'repo-9', factoryId: 'factory-tokyo', name: 'Energy Demand Forecasting', description: 'AI forecasting for factory energy demand, enabling optimal purchasing and load scheduling', stars: 5, forks: 4, isPublic: true, tags: ['energy', 'forecast', 'SOP-E-001'], language: 'Energy', lastUpdated: '2026-02-09T06:00:00Z', createdAt: '2025-03-10T09:00:00Z' },
    { id: 'repo-10', factoryId: 'factory-tokyo', name: 'Predictive Maintenance Suite', description: 'Comprehensive condition monitoring across all equipment types with unified alerting', stars: 5, forks: 5, isPublic: true, tags: ['predictive', 'maintenance', 'SOP-M-001'], language: 'General', lastUpdated: '2026-02-08T22:00:00Z', createdAt: '2024-11-05T08:00:00Z' },
    { id: 'repo-11', factoryId: 'factory-tokyo', name: 'OEE Real-Time Dashboard', description: 'Live OEE calculation with automatic root cause analysis for availability losses', stars: 4, forks: 3, isPublic: true, tags: ['oee', 'metrics', 'SOP-K-002'], language: 'Analytics', lastUpdated: '2026-02-06T18:00:00Z', createdAt: '2025-01-20T10:00:00Z' },
    { id: 'repo-12', factoryId: 'factory-saopaulo', name: 'Humidity Control Procedure', description: 'Automated humidity regulation for moisture-sensitive manufacturing areas', stars: 2, forks: 0, isPublic: true, tags: ['humidity', 'environment', 'SOP-E-012'], language: 'Environment', lastUpdated: '2026-02-03T11:00:00Z', createdAt: '2025-11-28T14:00:00Z' },
]

// ─── Mock Feed Posts ─────────────────────────────────────────────
const MOCK_FEED: OpshubPost[] = [
    {
        id: 'post-1',
        type: 'insight',
        authorType: 'ai_agent',
        authorId: 'factory-munich',
        authorName: 'Munich AI Monitor',
        title: 'Workflow Triggered: Bearing Replacement Protocol - Motor A7',
        content: `Vibration RMS crossed 4.2 mm/s threshold (limit: 4.5). AI confidence: 91%.\n**Estimated remaining useful life: 72 hours.**\n\n**Auto-actions executed:**\nWork Order WO-4821 created, assigned to Technician\nSpare part SKF-6205 reserved from warehouse (2 in stock)\nSOP-M-047 attached (bearing replacement procedure)\nProduction planning notified\n\n**Estimated savings:** EUR 8,500 in avoided unplanned downtime`,
        workflowRepoRef: 'repo-3',
        tags: ['predictive', 'motors', 'line-3', 'automated', 'work-order'],
        upvotes: 67,
        comments: 8,
        createdAt: '2026-02-09T14:30:00Z',
        status: 'resolved',
    },
    {
        id: 'post-2',
        type: 'anomaly_alert',
        authorType: 'ai_agent',
        authorId: 'factory-shanghai',
        authorName: 'Cross-Facility AI',
        title: 'Cross-Facility Alert: Pattern Match Detected',
        content: `**Motor B12 (Shanghai)** shows vibration signature **87% similar** to Motor A7 failure pattern (Munich, resolved Jan 15).\n\nThe Munich team replaced the bearing proactively and avoided 14 hours of unplanned downtime.\n\n**Suggested action:** Apply Munich's Bearing Replacement Protocol proactively.\n**If approved, estimated savings:** $12,000 in unplanned downtime avoided.`,
        anomalyRef: 'anomaly-cross-1',
        workflowRepoRef: 'repo-3',
        tags: ['cross-facility', 'pattern-match', 'motors', 'proactive'],
        upvotes: 89,
        comments: 23,
        createdAt: '2026-02-09T12:15:00Z',
        status: 'pending',
        sourceFacilityId: 'factory-munich',
        targetFacilityId: 'factory-shanghai',
    },
    {
        id: 'post-3',
        type: 'question',
        authorType: 'human',
        authorId: 'factory-detroit',
        authorName: 'John Martinez, Maintenance Supervisor',
        title: 'Motor on Line 3 vibrating unusually - what should I check first?',
        content: `The pump on Line 3 started making a different noise during second shift. Vibration readings are at 3.8 mm/s (usually around 2.1).\n\nThe technician says he changed the filter yesterday but the data doesn't match up - consumption went up, not down.\n\nHas anyone seen this pattern before?`,
        tags: ['motors', 'vibration', 'troubleshooting', 'line-3'],
        upvotes: 34,
        comments: 12,
        createdAt: '2026-02-09T10:00:00Z',
        status: 'open',
    },
    {
        id: 'post-4',
        type: 'pull_request',
        authorType: 'human',
        authorId: 'factory-munich',
        authorName: 'Anna Schmidt, Reliability Engineer',
        title: 'Workflow Improvement: Add acoustic analysis to Bearing Early Warning',
        content: `After analyzing 2,847 bearing failures across our fleet, we found that adding acoustic frequency analysis to vibration monitoring improves prediction accuracy from 82% to 93%.\n\n**Proposed changes to SOP-M-047:**\n- Add FFT analysis layer to existing vibration protocol\n- New threshold tuning for industrial frequencies (500Hz-2kHz)\n- Compatible with existing sensor infrastructure\n\n**Impact:** 40% reduction in false positives.`,
        workflowRepoRef: 'repo-3',
        tags: ['workflow-improvement', 'bearings', 'acoustic', 'SOP-M-047'],
        upvotes: 56,
        comments: 18,
        createdAt: '2026-02-08T16:00:00Z',
        status: 'pending',
    },
    {
        id: 'post-5',
        type: 'insight',
        authorType: 'ai_agent',
        authorId: 'factory-munich',
        authorName: 'Munich Efficiency Bot',
        title: 'Weekly Report: Motor Zone achieved 97.2% uptime - EUR 47,000 saved',
        content: `After implementing the **Bearing Failure Early Warning** workflow last month, Motor Zone performance improved significantly.\n\n**23 consecutive days** without unplanned downtime.\n**Estimated monthly savings:** EUR 47,000\n\n**Recommendation:** Propagate this workflow to Shanghai and Detroit facilities.`,
        workflowRepoRef: 'repo-3',
        tags: ['efficiency', 'success', 'monthly-report', 'motors'],
        upvotes: 112,
        comments: 15,
        createdAt: '2026-02-08T08:00:00Z',
    },
    {
        id: 'post-6',
        type: 'issue',
        authorType: 'human',
        authorId: 'factory-saopaulo',
        authorName: 'Carlos Silva, Night Shift Lead',
        title: 'Humidity workflow triggering false alarms at night (2-4 AM)',
        content: `The Humidity Control Procedure is detecting high-humidity alerts between 2-4 AM every night this week. Manual sensor check shows normal readings.\n\n**Suspected cause:** Sensor warm-up time after brief power cycles during shift change.\n\n**Request:** Can we add a 10-minute stabilization delay after power restore before triggering alerts?`,
        workflowRepoRef: 'repo-12',
        tags: ['bug', 'humidity', 'sensors', 'false-alarms'],
        upvotes: 18,
        comments: 6,
        createdAt: '2026-02-07T19:30:00Z',
        status: 'open',
    },
    {
        id: 'post-7',
        type: 'announcement',
        authorType: 'system',
        authorId: 'system',
        authorName: 'OpsHub System',
        title: 'New: Cross-Facility Workflow Adoption now available',
        content: `You can now **adopt workflows** from other facilities directly!\n\n**How it works:**\n1. Browse proven workflows from high-performing facilities\n2. Click "Adopt Workflow" to apply it to your site\n3. Customize thresholds and parameters for your equipment\n4. Share improvements back to benefit everyone`,
        tags: ['feature', 'announcement', 'cross-facility'],
        upvotes: 203,
        comments: 45,
        createdAt: '2026-02-06T12:00:00Z',
    },
    {
        id: 'post-8',
        type: 'insight',
        authorType: 'ai_agent',
        authorId: 'factory-detroit',
        authorName: 'Detroit Weld AI',
        title: 'Discovery: Optimal weld parameters for aluminum 6061-T6 identified',
        content: `After analyzing 2,847 weld cycles, identified parameters with 99.7% quality pass rate (vs 94.2% default).\n\n**Impact:** 58% reduction in rework, estimated EUR 15,000/month savings.\n\n**Action:** These parameters have been added to SOP-W-011. Other facilities with aluminum welding can adopt.`,
        workflowRepoRef: 'repo-8',
        tags: ['welding', 'aluminum', 'parameters', 'optimization'],
        upvotes: 94,
        comments: 22,
        createdAt: '2026-02-05T15:45:00Z',
    },
    {
        id: 'post-9',
        type: 'discussion',
        authorType: 'human',
        authorId: 'factory-munich',
        authorName: 'Omar Khalid, Reliability Engineer',
        title: 'WO-2026-0847: Root cause confirmed - Sensor HS-7A fault',
        content: `Investigation complete on Paint Booth #7 humidity issue. **Root cause:** Sensor HS-7A showing intermittent fault — response time degraded from 2s to 12s.\n\nHVAC ducting is clear, no mechanical issues. Recommending sensor replacement with spare HS-VAISALA-HMT120.\n\n@Sarah Chen - approval needed for parts requisition.`,
        tags: ['discussion', 'paint', 'investigation', 'work-order'],
        upvotes: 12,
        comments: 5,
        createdAt: '2026-02-09T11:50:00Z',
    },
    {
        id: 'post-10',
        type: 'workflow_execution',
        authorType: 'ai_agent',
        authorId: 'factory-shanghai',
        authorName: 'Shanghai Automation',
        title: 'Workflow Executed: Assembly Line Balancing - Line 4',
        content: `**Assembly Line Balancing** workflow auto-triggered on Line 4 due to bottleneck detection at Station 7.\n\n**Actions taken:**\n- Redistributed workload across stations 5-9\n- Adjusted cycle times: -8s Station 7, +3s Station 6\n- Real-time throughput increased from 42 to 48 units/hour\n\n**Result:** Bottleneck eliminated. Line efficiency improved 14%.`,
        workflowRepoRef: 'repo-4',
        tags: ['workflow', 'assembly', 'automation', 'line-4'],
        upvotes: 45,
        comments: 8,
        createdAt: '2026-02-09T08:30:00Z',
        status: 'merged',
    },
    {
        id: 'post-11',
        type: 'discussion',
        authorType: 'human',
        authorId: 'factory-detroit',
        authorName: 'Ahmed Nasser, Maintenance Lead',
        title: 'WO-2026-0839: Bearing replacement completed successfully',
        content: `Motor A7 bearing replacement finished ahead of schedule. New SKF-6205 bearing installed and tested.\n\n**Post-replacement vibration:** 1.8 mm/s (well below 4.5 threshold)\n**Downtime:** 3.5 hours (vs estimated 6 hours)\n\nMotor back in service. Thanks to @Lisa Park for the quick verification testing.`,
        tags: ['discussion', 'motors', 'maintenance', 'success'],
        upvotes: 28,
        comments: 7,
        createdAt: '2026-02-08T18:15:00Z',
    },
    {
        id: 'post-12',
        type: 'workflow_execution',
        authorType: 'ai_agent',
        authorId: 'factory-tokyo',
        authorName: 'Tokyo Energy AI',
        title: 'Workflow Executed: Energy Demand Forecasting - Daily Optimization',
        content: `**Energy Demand Forecasting** workflow completed daily optimization cycle.\n\n**Forecast accuracy:** 96.2% (vs 94.1% last week)\n**Peak load prediction:** 2,847 kW at 14:30 (actual: 2,831 kW)\n**Cost optimization:** Shifted 340 kW load to off-peak hours\n\n**Estimated daily savings:** EUR 1,240`,
        workflowRepoRef: 'repo-9',
        tags: ['workflow', 'energy', 'forecast', 'optimization'],
        upvotes: 67,
        comments: 15,
        createdAt: '2026-02-08T16:00:00Z',
        status: 'merged',
    },
    {
        id: 'post-13',
        type: 'discussion',
        authorType: 'human',
        authorId: 'factory-saopaulo',
        authorName: 'Carlos Silva, Night Shift Lead',
        title: 'False alarms on humidity workflow - need help troubleshooting',
        content: `Getting repeated false alarms from the Humidity Control Procedure between 2-4 AM every night this week. Manual sensor checks show normal readings (48-52% RH).\n\nI think it's related to sensor warm-up after brief power cycles during shift change, but not 100% sure.\n\nHas anyone else seen this pattern? Any suggestions for troubleshooting?`,
        workflowRepoRef: 'repo-12',
        tags: ['discussion', 'humidity', 'troubleshooting', 'help-needed'],
        upvotes: 15,
        comments: 9,
        createdAt: '2026-02-07T20:00:00Z',
        status: 'open',
    },
    {
        id: 'post-14',
        type: 'workflow_execution',
        authorType: 'ai_agent',
        authorId: 'factory-munich',
        authorName: 'Munich Predictive AI',
        title: 'Workflow Executed: Bearing Failure Early Warning - Motor B3',
        content: `**Bearing Failure Early Warning** workflow triggered for Motor B3 on Line 2.\n\n**Detection:** Vibration RMS 3.9 mm/s, acoustic signature shows early bearing wear\n**Estimated RUL:** 96 hours\n**Auto-actions:**\n- Work Order WO-2026-0852 created\n- Spare part SKF-6204 reserved (3 in stock)\n- Maintenance scheduled for Thursday 06:00\n\n**Estimated savings:** EUR 7,200 in avoided downtime`,
        workflowRepoRef: 'repo-3',
        tags: ['workflow', 'predictive', 'motors', 'automated'],
        upvotes: 52,
        comments: 11,
        createdAt: '2026-02-07T14:45:00Z',
        status: 'resolved',
    },
    {
        id: 'post-15',
        type: 'discussion',
        authorType: 'human',
        authorId: 'factory-tokyo',
        authorName: 'Lisa Park, Reliability Engineer',
        title: 'Cross-facility learning: Munich\'s bearing protocol is excellent',
        content: `Just reviewed Munich's **Bearing Failure Early Warning** workflow after it was shared with our facility. The acoustic analysis layer they added is brilliant!\n\nWe're adapting it for our motor fleet. Initial testing shows 91% prediction accuracy vs our current 78%.\n\nBig thanks to @Anna Schmidt and the Munich team for sharing this. This is exactly what cross-facility learning should be!`,
        workflowRepoRef: 'repo-3',
        tags: ['discussion', 'cross-facility', 'learning', 'appreciation'],
        upvotes: 89,
        comments: 24,
        createdAt: '2026-02-06T16:30:00Z',
    },
]

// ─── Mock Anomalies ──────────────────────────────────────────────
const MOCK_ANOMALIES: DetectedAnomaly[] = [
    {
        id: 'anomaly-1',
        factoryId: 'factory-munich',
        factoryName: 'Munich Plant',
        equipmentId: 'eq-paint-booth-3',
        equipmentName: 'Paint Booth #3 - Drying Section',
        equipmentType: 'Paint',
        severity: 'critical',
        description: 'Temperature spike: 42°C (normal: 22-28°C). Possible heating element malfunction or ventilation blockage.',
        detectedAt: '2026-02-11T07:15:00Z',
        suggestedWorkflowId: 'repo-7',
        suggestedWorkflowName: 'Paint Booth Temperature Control',
        suggestedAction: 'Isolate booth, inspect heating element and ventilation',
        status: 'pending',
        confidence: 0.91,
        remainingUsefulLife: '4 hours',
        estimatedCostIfIgnored: 28000,
        digitalTwinAssetId: 'paint-booth-3',
    },
    {
        id: 'anomaly-2',
        factoryId: 'factory-munich',
        factoryName: 'Munich Plant',
        equipmentId: 'eq-motor-a7',
        equipmentName: 'Motor A7 - Conveyor Drive Line 3',
        equipmentType: 'Motors',
        severity: 'high',
        description: 'Vibration RMS at 4.2 mm/s (threshold: 4.5). Pattern matches bearing degradation signature with 87% confidence.',
        detectedAt: '2026-02-09T14:20:00Z',
        suggestedWorkflowId: 'repo-3',
        suggestedWorkflowName: 'Bearing Failure Early Warning',
        suggestedAction: 'Schedule bearing replacement within 72h, reserve SKF-6205 from warehouse',
        status: 'pending',
        confidence: 0.87,
        remainingUsefulLife: '72 hours',
        estimatedCostIfIgnored: 8500,
        digitalTwinAssetId: 'motor-a7',
    },
    {
        id: 'anomaly-3',
        factoryId: 'factory-detroit',
        factoryName: 'Detroit Assembly',
        equipmentId: 'eq-robot-kr300-2',
        equipmentName: 'KUKA KR300 #2 - Welding Cell',
        equipmentType: 'Robotics',
        severity: 'medium',
        description: 'Positional accuracy drift: 0.3mm from calibration baseline. Quality risk if exceeds 0.5mm tolerance.',
        detectedAt: '2026-02-09T11:00:00Z',
        suggestedWorkflowId: 'repo-6',
        suggestedWorkflowName: 'Robot Arm Calibration Check',
        suggestedAction: 'Run automated recalibration during next planned maintenance window',
        status: 'investigating',
        confidence: 0.78,
        remainingUsefulLife: '5 days',
        estimatedCostIfIgnored: 4200,
        digitalTwinAssetId: 'kuka-kr300-2',
    },
    {
        id: 'anomaly-4',
        factoryId: 'factory-tokyo',
        factoryName: 'Tokyo Innovation Lab',
        equipmentId: 'eq-hvac-zone-b',
        equipmentName: 'HVAC Zone B Controller',
        equipmentType: 'HVAC',
        severity: 'low',
        description: 'Energy consumption 8% above baseline. Air filter may need replacement.',
        detectedAt: '2026-02-09T09:30:00Z',
        suggestedWorkflowId: 'repo-2',
        suggestedWorkflowName: 'HVAC Energy Savings Routine',
        suggestedAction: 'Check and replace air filters if dirty',
        status: 'pending',
        confidence: 0.65,
        remainingUsefulLife: '14 days',
        estimatedCostIfIgnored: 1200,
        digitalTwinAssetId: 'hvac-zone-b',
    },
]

// ─── Mock Changelog ──────────────────────────────────────────────
const MOCK_CHANGELOG: ChangelogEntry[] = [
    { id: 'cl-1', date: '2026-02-09T14:00:00Z', title: 'Tokyo: Energy forecast model v2.3 — 15% accuracy improvement', description: 'New weather integration reduced prediction error, saving EUR 3,200/week in energy costs', factoryId: 'factory-tokyo', workflowRepoId: 'repo-9', type: 'release' },
    { id: 'cl-2', date: '2026-02-08T16:30:00Z', title: 'Munich: Bearing prediction saved EUR 47K this month', description: '23 days without unplanned motor downtime', factoryId: 'factory-munich', type: 'insight' },
    { id: 'cl-3', date: '2026-02-07T10:00:00Z', title: 'Shanghai: Quality vision -> MES integration live', description: 'Defects now auto-logged, reducing paperwork 4 hours/day', factoryId: 'factory-shanghai', workflowRepoId: 'repo-5', type: 'integration' },
    { id: 'cl-4', date: '2026-02-06T12:00:00Z', title: 'Cross-facility workflow adoption launched', description: 'Facilities can now adopt proven workflows from top performers', type: 'improvement' },
    { id: 'cl-5', date: '2026-02-05T09:00:00Z', title: 'Detroit: Weld quality monitoring expanded — 58% less rework', description: 'AI-optimized parameters now cover all 12 welding stations', factoryId: 'factory-detroit', workflowRepoId: 'repo-8', type: 'improvement' },
    { id: 'cl-6', date: '2026-02-04T14:30:00Z', title: 'Global: AI insight engine upgraded', description: 'Cross-facility pattern matching now detects similar failures 3x faster', type: 'release' },
    { id: 'cl-7', date: '2026-02-03T11:00:00Z', title: 'Sao Paulo: Humidity control published — available for adoption', description: 'Reduced product moisture defects 67% in sensitive manufacturing', factoryId: 'factory-saopaulo', workflowRepoId: 'repo-12', type: 'release' },
    { id: 'cl-8', date: '2026-02-02T08:00:00Z', title: 'Alert: 3 high-severity anomalies require attention', description: 'AI monitoring flagged critical equipment issues across Munich and Shanghai', type: 'alert' },
]

// ─── Execution Checklist Steps (Paint Booth #7 repair) ──────────
const MOCK_CHECKLIST_STEPS: ChecklistStep[] = [
    {
        id: 'step-1',
        order: 1,
        title: 'Isolate Paint Booth #7',
        instructions: 'Lock out power supply to Booth #7 humidity control unit. Tag out at panel CB-PB7. Verify zero energy state on local indicator.',
        caution: 'Booth may still contain volatile fumes. Ensure ventilation is running for minimum 15 minutes before entry.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '10 min',
        completed: false,
    },
    {
        id: 'step-2',
        order: 2,
        title: 'Inspect Humidity Sensors',
        instructions: 'Remove sensor housing cover (4x M4 bolts). Check for condensation, corrosion, or loose wiring on sensors HS-7A and HS-7B. Compare readings with portable reference hygrometer.',
        requiresPhoto: true,
        requiresSignoff: false,
        estimatedTime: '20 min',
        completed: false,
    },
    {
        id: 'step-3',
        order: 3,
        title: 'Check HVAC Ducting and Dampers',
        instructions: 'Inspect supply and return ducts for blockages. Verify damper positions on DA-7A and DA-7B match setpoints (supply: 65% open, return: 80% open). Check belt tension on AHU-7 fan.',
        caution: 'Ducts may be hot. Wear thermal gloves.',
        requiresPhoto: true,
        requiresSignoff: false,
        estimatedTime: '25 min',
        completed: false,
    },
    {
        id: 'step-4',
        order: 4,
        title: 'Replace Faulty Sensor (if confirmed)',
        instructions: 'If sensor fault confirmed, replace with spare from inventory (part: HS-VAISALA-HMT120). Calibrate new sensor using reference standard. Record new serial number in CMMS.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '15 min',
        completed: false,
    },
    {
        id: 'step-5',
        order: 5,
        title: 'Restore and Verify',
        instructions: 'Remove lockout/tagout. Power up humidity control unit. Monitor readings for 30 minutes. Confirm stable humidity within 40-55% RH range. Run one test panel through booth and verify adhesion quality.',
        requiresPhoto: true,
        requiresSignoff: true,
        estimatedTime: '45 min',
        completed: false,
    },
]

const MOCK_EXECUTION_CHECKLIST: ExecutionChecklist = {
    id: 'checklist-0847-t3',
    workOrderId: 'wo-0847',
    taskId: 'task-0847-3',
    title: 'Paint Booth #7 Humidity Sensor Inspection & Repair',
    steps: MOCK_CHECKLIST_STEPS,
}

// ─── Mock Tasks for WO-0847 ─────────────────────────────────────
const MOCK_TASKS_0847: WorkOrderTask[] = [
    {
        id: 'task-0847-1',
        number: 1,
        workOrderId: 'wo-0847',
        type: 'investigation',
        title: 'Investigate root cause of humidity sensor anomaly',
        description: 'Analyze sensor data logs from Paint Booth #7 over the last 48 hours. Cross-reference with HVAC system logs and ambient conditions. Determine if the erratic readings are from sensor fault, HVAC malfunction, or environmental factor.',
        assignee: MOCK_TEAM[1], // Omar
        assignedBy: MOCK_TEAM[0], // Sarah
        priority: 'critical',
        status: 'completed',
        dependsOn: [],
        isBlocked: false,
        updates: [
            {
                id: 'update-1a',
                author: MOCK_TEAM[1],
                content: 'Pulled 48h sensor logs. Humidity readings show erratic spikes correlating with HVAC cycle transitions. Checking damper actuator response times.',
                createdAt: '2026-02-09T10:30:00Z',
            },
            {
                id: 'update-1b',
                author: MOCK_TEAM[1],
                content: 'Root cause identified: Sensor HS-7A showing intermittent fault — response time degraded from 2s to 12s. HVAC ducting clear. Recommending sensor replacement.',
                createdAt: '2026-02-09T11:45:00Z',
            },
        ],
        createdAt: '2026-02-09T09:20:00Z',
        updatedAt: '2026-02-09T11:45:00Z',
    },
    {
        id: 'task-0847-2',
        number: 2,
        workOrderId: 'wo-0847',
        type: 'approval',
        title: 'Approve repair plan and parts requisition',
        description: 'Review investigation findings and approve the repair plan. Authorize parts requisition for replacement humidity sensor (HS-VAISALA-HMT120) from warehouse.',
        assignee: MOCK_TEAM[0], // Sarah
        assignedBy: MOCK_TEAM[0], // Sarah
        priority: 'critical',
        status: 'completed',
        dependsOn: ['task-0847-1'],
        isBlocked: false,
        updates: [
            {
                id: 'update-2a',
                author: MOCK_TEAM[0],
                content: 'Reviewed Omar\'s findings. Approving sensor replacement. Parts requisition PR-2026-1847 submitted. Sensor available in warehouse (2 in stock).',
                createdAt: '2026-02-09T12:00:00Z',
            },
        ],
        createdAt: '2026-02-09T11:50:00Z',
        updatedAt: '2026-02-09T12:00:00Z',
    },
    {
        id: 'task-0847-3',
        number: 3,
        workOrderId: 'wo-0847',
        type: 'execution',
        title: 'Execute sensor replacement on Paint Booth #7',
        description: 'Follow SOP-P-008 to replace humidity sensor HS-7A. Includes booth isolation, sensor swap, calibration, and system restoration. Full checklist attached.',
        assignee: MOCK_TEAM[2], // Ahmed
        assignedBy: MOCK_TEAM[0], // Sarah
        priority: 'critical',
        status: 'in-progress',
        dependsOn: ['task-0847-2'],
        isBlocked: false,
        checklist: MOCK_CHECKLIST_STEPS,
        updates: [
            {
                id: 'update-3a',
                author: MOCK_TEAM[2],
                content: 'Starting execution. Booth #7 isolated and locked out. Beginning sensor inspection.',
                createdAt: '2026-02-09T13:00:00Z',
            },
        ],
        createdAt: '2026-02-09T12:05:00Z',
        updatedAt: '2026-02-09T13:00:00Z',
    },
    {
        id: 'task-0847-4',
        number: 4,
        workOrderId: 'wo-0847',
        type: 'verification',
        title: 'Verify repair and validate booth operation',
        description: 'After sensor replacement, verify humidity readings are stable (40-55% RH). Run test panels through booth and confirm adhesion quality meets spec (pull test > 3.5 MPa). Monitor for 2 hours before clearing booth for production.',
        assignee: MOCK_TEAM[3], // Lisa
        assignedBy: MOCK_TEAM[0], // Sarah
        priority: 'high',
        status: 'pending',
        dependsOn: ['task-0847-3'],
        isBlocked: true,
        updates: [],
        createdAt: '2026-02-09T12:10:00Z',
        updatedAt: '2026-02-09T12:10:00Z',
    },
]

// ─── Mock Work Order WO-2026-0847 ───────────────────────────────
const MOCK_WORK_ORDER_0847: WorkOrderCard = {
    id: 'wo-0847',
    number: 'WO-2026-0847',
    title: 'Paint Booth #7 Humidity Control Failure',
    description: 'Critical humidity sensor anomaly detected in Paint Booth #7. Erratic readings (45% -> 78% -> 52% in 10 minutes) indicate sensor failure or HVAC malfunction. Paint adhesion quality at immediate risk. Production line impact: 12 vehicles/hour.',
    equipmentId: 'eq-paint-booth-7',
    equipmentName: 'Paint Booth #7 - Humidity Control Unit',
    status: 'in-progress',
    priority: 'critical',
    createdAt: '2026-02-09T09:18:00Z',
    owner: MOCK_TEAM[0], // Sarah Chen
    team: [MOCK_TEAM[0], MOCK_TEAM[1], MOCK_TEAM[2], MOCK_TEAM[3]],
    tags: ['paint', 'humidity', 'sensor-failure', 'critical', 'line-7'],
    linkedAnomalyId: 'anomaly-1',
    tasks: MOCK_TASKS_0847,
    facility: 'Munich Plant',
}

// ─── Additional Mock Work Orders ────────────────────────────────
const MOCK_WORK_ORDER_0839: WorkOrderCard = {
    id: 'wo-0839',
    number: 'WO-2026-0839',
    title: 'Motor A7 Bearing Replacement - Line 3',
    description: 'Vibration RMS at 4.2 mm/s. Pattern matches bearing degradation signature.',
    equipmentId: 'eq-motor-a7',
    equipmentName: 'Motor A7 - Conveyor Drive Line 3',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2026-02-08T14:20:00Z',
    owner: MOCK_TEAM[1],
    team: [MOCK_TEAM[1], MOCK_TEAM[2]],
    tags: ['motors', 'predictive', 'bearing'],
    linkedAnomalyId: 'anomaly-2',
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0821: WorkOrderCard = {
    id: 'wo-0821',
    number: 'WO-2026-0821',
    title: 'KUKA KR300 #2 Calibration Check',
    description: 'Positional accuracy drift: 0.3mm from calibration baseline.',
    equipmentId: 'eq-robot-kr300-2',
    equipmentName: 'KUKA KR300 #2 - Welding Cell',
    status: 'open',
    priority: 'medium',
    createdAt: '2026-02-07T11:00:00Z',
    owner: MOCK_TEAM[3],
    team: [MOCK_TEAM[3]],
    tags: ['robotics', 'calibration', 'kuka'],
    linkedAnomalyId: 'anomaly-3',
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0815: WorkOrderCard = {
    id: 'wo-0815',
    number: 'WO-2026-0815',
    title: 'HVAC Zone B Filter Replacement',
    description: 'Energy consumption 8% above baseline. Air filter needs replacement.',
    equipmentId: 'eq-hvac-zone-b',
    equipmentName: 'HVAC Zone B Controller',
    status: 'open',
    priority: 'low',
    createdAt: '2026-02-06T09:30:00Z',
    owner: MOCK_TEAM[2],
    team: [MOCK_TEAM[2]],
    tags: ['hvac', 'energy', 'maintenance'],
    linkedAnomalyId: 'anomaly-4',
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0803: WorkOrderCard = {
    id: 'wo-0803',
    number: 'WO-2026-0803',
    title: 'Conveyor Belt Tension Adjustment - Line 5',
    description: 'Belt slippage detected during peak load. Requires tension adjustment.',
    equipmentId: 'eq-conveyor-line5',
    equipmentName: 'Conveyor Belt - Line 5',
    status: 'resolved',
    priority: 'medium',
    createdAt: '2026-02-05T08:15:00Z',
    resolvedAt: '2026-02-05T16:30:00Z',
    owner: MOCK_TEAM[2],
    team: [MOCK_TEAM[2]],
    tags: ['conveyor', 'mechanical', 'line-5'],
    tasks: [],
    facility: 'Munich Plant',
    costSaved: 2400,
}

const MOCK_WORK_ORDER_0798: WorkOrderCard = {
    id: 'wo-0798',
    number: 'WO-2026-0798',
    title: 'Pump P-14 Seal Replacement',
    description: 'Minor leak detected at pump seal. Preventive replacement scheduled.',
    equipmentId: 'eq-pump-p14',
    equipmentName: 'Coolant Pump P-14',
    status: 'resolved',
    priority: 'medium',
    createdAt: '2026-02-04T10:00:00Z',
    resolvedAt: '2026-02-04T14:45:00Z',
    owner: MOCK_TEAM[2],
    team: [MOCK_TEAM[2]],
    tags: ['pumps', 'seals', 'preventive'],
    tasks: [],
    facility: 'Munich Plant',
    costSaved: 1800,
}

const MOCK_WORK_ORDER_0785: WorkOrderCard = {
    id: 'wo-0785',
    number: 'WO-2026-0785',
    title: 'Weld Quality Inspection - Cell 3',
    description: 'Routine quality inspection for welding cell 3 after parameter update.',
    equipmentId: 'eq-weld-cell3',
    equipmentName: 'Welding Cell 3',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-03T07:00:00Z',
    resolvedAt: '2026-02-03T12:00:00Z',
    owner: MOCK_TEAM[3],
    team: [MOCK_TEAM[3]],
    tags: ['welding', 'quality', 'inspection'],
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0772: WorkOrderCard = {
    id: 'wo-0772',
    number: 'WO-2026-0772',
    title: 'Temperature Sensor Calibration - Paint Booth #3',
    description: 'Annual calibration check for temperature sensors in paint booth.',
    equipmentId: 'eq-paint-booth-3',
    equipmentName: 'Paint Booth #3 - Temperature Control',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-02T08:30:00Z',
    resolvedAt: '2026-02-02T11:15:00Z',
    owner: MOCK_TEAM[1],
    team: [MOCK_TEAM[1]],
    tags: ['paint', 'sensors', 'calibration'],
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0765: WorkOrderCard = {
    id: 'wo-0765',
    number: 'WO-2026-0765',
    title: 'Assembly Line Robot Arm Lubrication',
    description: 'Scheduled lubrication maintenance for assembly line robot arms.',
    equipmentId: 'eq-robot-assembly',
    equipmentName: 'Assembly Robot Arms - Line 2',
    status: 'closed',
    priority: 'low',
    createdAt: '2026-02-01T06:00:00Z',
    resolvedAt: '2026-02-01T09:30:00Z',
    owner: MOCK_TEAM[2],
    team: [MOCK_TEAM[2]],
    tags: ['robotics', 'lubrication', 'preventive'],
    tasks: [],
    facility: 'Munich Plant',
}

const MOCK_WORK_ORDER_0758: WorkOrderCard = {
    id: 'wo-0758',
    number: 'WO-2026-0758',
    title: 'Electrical Panel Inspection - Zone A',
    description: 'Quarterly electrical panel inspection and thermal imaging scan.',
    equipmentId: 'eq-panel-zonea',
    equipmentName: 'Electrical Panel - Zone A',
    status: 'closed',
    priority: 'medium',
    createdAt: '2026-01-31T07:30:00Z',
    resolvedAt: '2026-01-31T13:00:00Z',
    owner: MOCK_TEAM[1],
    team: [MOCK_TEAM[1]],
    tags: ['electrical', 'inspection', 'preventive'],
    tasks: [],
    facility: 'Munich Plant',
}

const ALL_MOCK_WORK_ORDERS = [
    MOCK_WORK_ORDER_0847,
    MOCK_WORK_ORDER_0839,
    MOCK_WORK_ORDER_0821,
    MOCK_WORK_ORDER_0815,
    MOCK_WORK_ORDER_0803,
    MOCK_WORK_ORDER_0798,
    MOCK_WORK_ORDER_0785,
    MOCK_WORK_ORDER_0772,
    MOCK_WORK_ORDER_0765,
    MOCK_WORK_ORDER_0758,
]

// ─── Mock Activity Entries (full timeline for WO-0847) ──────────
const MOCK_ACTIVITY_ENTRIES: ActivityEntry[] = [
    {
        id: 'act-1',
        workOrderId: 'wo-0847',
        action: 'anomaly-detected',
        actor: { id: 'ai-monitor', name: 'Munich AI Monitor', role: 'AI Agent' },
        description: 'Anomaly detected: Paint Booth #7 humidity readings erratic',
        details: 'Humidity oscillating 45-78% RH over 10-minute window. Confidence: 94%.',
        timestamp: '2026-02-09T09:15:00Z',
        metadata: { anomalyId: 'anomaly-1', confidence: 0.94 },
    },
    {
        id: 'act-2',
        workOrderId: 'wo-0847',
        action: 'work-order-created',
        actor: { id: 'ai-monitor', name: 'Munich AI Monitor', role: 'AI Agent' },
        description: 'Work order WO-2026-0847 created automatically',
        details: 'Priority: Critical. Assigned to Sarah Chen (Plant Manager).',
        timestamp: '2026-02-09T09:18:00Z',
    },
    {
        id: 'act-3',
        workOrderId: 'wo-0847',
        action: 'task-assigned',
        actor: MOCK_TEAM[0],
        description: 'Investigation task assigned to Omar Khalid',
        details: 'Task #1: Investigate root cause of humidity sensor anomaly',
        timestamp: '2026-02-09T09:20:00Z',
    },
    {
        id: 'act-4',
        workOrderId: 'wo-0847',
        action: 'task-accepted',
        actor: MOCK_TEAM[1],
        description: 'Omar Khalid accepted investigation task',
        timestamp: '2026-02-09T09:25:00Z',
    },
    {
        id: 'act-5',
        workOrderId: 'wo-0847',
        action: 'task-started',
        actor: MOCK_TEAM[1],
        description: 'Omar Khalid started investigation',
        details: 'Pulling 48h sensor logs from historian.',
        timestamp: '2026-02-09T09:30:00Z',
    },
    {
        id: 'act-6',
        workOrderId: 'wo-0847',
        action: 'comment-posted',
        actor: MOCK_TEAM[1],
        description: 'Omar posted investigation update',
        details: 'Erratic spikes correlating with HVAC cycle transitions. Checking damper actuator response times.',
        timestamp: '2026-02-09T10:30:00Z',
    },
    {
        id: 'act-7',
        workOrderId: 'wo-0847',
        action: 'finding-shared',
        actor: MOCK_TEAM[1],
        description: 'Root cause identified: Sensor HS-7A intermittent fault',
        details: 'Response time degraded from 2s to 12s. HVAC ducting clear. Recommending sensor replacement.',
        timestamp: '2026-02-09T11:45:00Z',
    },
    {
        id: 'act-8',
        workOrderId: 'wo-0847',
        action: 'task-completed',
        actor: MOCK_TEAM[1],
        description: 'Investigation task completed by Omar Khalid',
        timestamp: '2026-02-09T11:48:00Z',
    },
    {
        id: 'act-9',
        workOrderId: 'wo-0847',
        action: 'task-assigned',
        actor: MOCK_TEAM[0],
        description: 'Approval task assigned to Sarah Chen',
        details: 'Task #2: Review findings and approve repair plan.',
        timestamp: '2026-02-09T11:50:00Z',
    },
    {
        id: 'act-10',
        workOrderId: 'wo-0847',
        action: 'task-completed',
        actor: MOCK_TEAM[0],
        description: 'Sarah Chen approved repair plan',
        details: 'Parts requisition PR-2026-1847 submitted. Sensor available (2 in stock).',
        timestamp: '2026-02-09T12:00:00Z',
    },
    {
        id: 'act-11',
        workOrderId: 'wo-0847',
        action: 'task-assigned',
        actor: MOCK_TEAM[0],
        description: 'Execution task assigned to Ahmed Nasser',
        details: 'Task #3: Execute sensor replacement per SOP-P-008.',
        timestamp: '2026-02-09T12:05:00Z',
    },
    {
        id: 'act-12',
        workOrderId: 'wo-0847',
        action: 'task-accepted',
        actor: MOCK_TEAM[2],
        description: 'Ahmed Nasser accepted execution task',
        timestamp: '2026-02-09T12:15:00Z',
    },
    {
        id: 'act-13',
        workOrderId: 'wo-0847',
        action: 'task-started',
        actor: MOCK_TEAM[2],
        description: 'Ahmed Nasser started booth isolation',
        details: 'Booth #7 isolated and locked out.',
        timestamp: '2026-02-09T13:00:00Z',
    },
    {
        id: 'act-14',
        workOrderId: 'wo-0847',
        action: 'checklist-step-completed',
        actor: MOCK_TEAM[2],
        description: 'Step 1 completed: Isolate Paint Booth #7',
        details: 'Lockout/tagout verified. Zero energy confirmed.',
        timestamp: '2026-02-09T13:12:00Z',
    },
    {
        id: 'act-15',
        workOrderId: 'wo-0847',
        action: 'ai-recommendation-generated',
        actor: { id: 'ai-recommendation-engine', name: 'OpsHub AI Agent', role: 'AI Agent' },
        description: 'AI generated preventive workflow recommendation',
        details: 'Pattern analysis across 3 facilities suggests automated humidity monitoring workflow could prevent 85% of similar incidents.',
        timestamp: '2026-02-09T13:30:00Z',
        metadata: { recommendationId: 'rec-0847' },
    },
]

// ─── Mock Discussion Comments ────────────────────────────────────
const MOCK_DISCUSSION: DiscussionComment[] = [
    {
        id: 'disc-1',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[0],
        content: 'I\'ve assigned this as critical priority. Paint Booth #7 affects 12 vehicles/hour. Omar, please prioritize the investigation. Ahmed, stand by for execution once we have the root cause.',
        mentions: ['omar-khalid', 'ahmed-nasser'],
        createdAt: '2026-02-09T09:22:00Z',
        reactions: [{ emoji: '👍', count: 2 }],
    },
    {
        id: 'disc-2',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[1],
        content: 'On it. Initial look at the data — the humidity spikes are correlating with HVAC transition cycles. This might be a sensor response time issue rather than actual humidity swings. Pulling detailed logs now.',
        mentions: [],
        createdAt: '2026-02-09T10:30:00Z',
    },
    {
        id: 'disc-3',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[1],
        content: 'Confirmed: Sensor HS-7A is the culprit. Response time degraded from spec 2s to measured 12s. When the HVAC cycles, the slow sensor can\'t track the transient and reports wild values. HS-7B reads clean. Recommendation: replace HS-7A with spare from warehouse.',
        mentions: ['sarah-chen'],
        createdAt: '2026-02-09T11:45:00Z',
        reactions: [{ emoji: '🎯', count: 3 }],
    },
    {
        id: 'disc-4',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[0],
        content: 'Good work Omar. Approved the replacement. Ahmed, you\'re cleared to proceed. Lisa, please be ready for verification once Ahmed finishes.',
        mentions: ['ahmed-nasser', 'lisa-park'],
        createdAt: '2026-02-09T12:02:00Z',
    },
    {
        id: 'disc-5',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[2],
        content: 'Copy that. Heading to Booth #7 now. Will start with lockout/tagout per SOP-P-008. Estimated completion: 2 hours.',
        mentions: [],
        createdAt: '2026-02-09T12:20:00Z',
    },
    {
        id: 'disc-6',
        workOrderId: 'wo-0847',
        author: MOCK_TEAM[3],
        content: 'Standing by for verification. I\'ll prepare the pull test equipment and reference hygrometer so we can validate immediately after Ahmed finishes.',
        mentions: [],
        createdAt: '2026-02-09T12:30:00Z',
    },
]

// ─── Mock AI Recommendation ─────────────────────────────────────
const MOCK_AI_RECOMMENDATION: AIAgentRecommendation = {
    id: 'rec-0847',
    workOrderId: 'wo-0847',
    generatedAt: '2026-02-09T13:30:00Z',
    status: 'pending-review',
    workflow: {
        id: 'wf-gen-humidity-monitor',
        name: 'Automated Humidity Sensor Health Monitor',
        description: 'Proactive monitoring workflow that detects humidity sensor degradation before it causes erratic readings. Triggers maintenance alert when response time exceeds 5s threshold.',
        version: '1.0.0-draft',
        trigger: {
            type: 'sensor-threshold',
            description: 'Monitor humidity sensor response time continuously',
            config: { metric: 'sensor_response_time', threshold: 5, unit: 'seconds', window: '5m' },
        },
        conditions: [
            {
                type: 'correlation-check',
                description: 'Verify HVAC is cycling (not a genuine humidity event)',
                config: { correlateWith: 'hvac_cycle_state', minCorrelation: 0.7 },
            },
            {
                type: 'persistence-check',
                description: 'Confirm degradation persists across 3 consecutive HVAC cycles',
                config: { minOccurrences: 3, timeWindow: '30m' },
            },
        ],
        actions: [
            {
                type: 'create-work-order',
                description: 'Auto-create maintenance work order for sensor inspection',
                config: { priority: 'high', template: 'sensor-replacement', assignTo: 'maintenance-lead' },
            },
            {
                type: 'notify-team',
                description: 'Alert reliability engineering team',
                config: { channel: 'reliability-eng', urgency: 'high' },
            },
            {
                type: 'reserve-parts',
                description: 'Pre-reserve replacement sensor from inventory',
                config: { partNumber: 'HS-VAISALA-HMT120', quantity: 1 },
            },
        ],
        generatedFrom: {
            anomalyPattern: 'humidity-sensor-degradation-wo-0847',
            sensorThresholds: [
                { metric: 'response_time', operator: '>', value: 5, unit: 'seconds' },
                { metric: 'reading_variance', operator: '>', value: 15, unit: 'percent_rh' },
            ],
            correlations: [
                'HVAC cycle transitions correlate with erratic readings when sensor response > 5s',
                'Sensor degradation follows exponential curve — detectable 48-72h before critical failure',
            ],
        },
    },
    sop: {
        id: 'sop-gen-humidity-sensor',
        title: 'Humidity Sensor Inspection and Replacement Procedure',
        version: '1.0.0-draft',
        description: 'Generated from WO-2026-0847 resolution. Standard procedure for inspecting and replacing humidity sensors in paint booth environments.',
        basedOn: 'WO-2026-0847 resolution by Omar Khalid and Ahmed Nasser',
        steps: [
            { order: 1, title: 'Isolate Equipment', instructions: 'Lock out power supply to humidity control unit. Tag out at designated panel. Verify zero energy state.', caution: 'Booth may contain volatile fumes. Ensure ventilation running 15+ minutes before entry.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '10 min', sourceNote: 'Based on SOP-P-008 Step 1' },
            { order: 2, title: 'Inspect Sensor Array', instructions: 'Remove sensor housing cover. Check for condensation, corrosion, or loose wiring. Compare readings with portable reference hygrometer.', requiresPhoto: true, requiresSignoff: false, estimatedTime: '20 min', sourceNote: 'Omar Khalid investigation findings' },
            { order: 3, title: 'Test Sensor Response Time', instructions: 'Use calibrated humidity generator to step-test sensor response. Measure T90 response time. Spec: < 5 seconds.', requiresPhoto: false, requiresSignoff: false, estimatedTime: '15 min', sourceNote: 'New step — derived from root cause analysis' },
            { order: 4, title: 'Replace Faulty Sensor', instructions: 'If response time > 5s or visual defects found, replace with HS-VAISALA-HMT120. Calibrate using reference standard. Record serial in CMMS.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '15 min' },
            { order: 5, title: 'Restore and Validate', instructions: 'Remove lockout/tagout. Power up. Monitor readings 30 minutes. Confirm stable 40-55% RH. Run test panel and verify adhesion > 3.5 MPa.', requiresPhoto: true, requiresSignoff: true, estimatedTime: '45 min' },
        ],
        safetyNotes: [
            'Always verify booth ventilation before entry',
            'Wear thermal gloves when inspecting HVAC ducts',
            'Follow site-specific lockout/tagout procedures',
        ],
        partsRequired: [
            { partName: 'Humidity Sensor', partNumber: 'HS-VAISALA-HMT120', quantity: 1 },
            { partName: 'Sensor Housing Gasket', partNumber: 'GSK-HMT120-SEAL', quantity: 1 },
        ],
        estimatedDuration: '1h 45min',
        toolsRequired: ['Torque wrench (M4)', 'Portable hygrometer', 'Humidity generator (calibrated)', 'Multimeter', 'Thermal gloves'],
    },
    summary: {
        patternDetected: 'Humidity sensor degradation follows predictable exponential curve, detectable 48-72 hours before critical failure through response time monitoring',
        dataSourcesUsed: [
            'WO-2026-0847 sensor logs (48h)',
            'HVAC system transition data',
            'Historical sensor failure database (3 facilities, 24 months)',
            'Manufacturer spec sheets (Vaisala HMT120)',
        ],
        confidenceScore: 0.91,
        estimatedPreventionValue: 45000,
        estimatedEarlyDetection: '48-72 hours before critical failure',
        applicableFacilities: ['Munich Plant', 'Shanghai Facility', 'Riyadh Manufacturing'],
    },
}

// ─── Hook ────────────────────────────────────────────────────────
export function useOpshubMockData() {
    const store = useOpshubStore()

    useEffect(() => {
        if (store.factories.length === 0) {
            store.setFactories(MOCK_FACTORIES)
            store.setWorkflowRepos(MOCK_REPOS)
            store.setFeed(MOCK_FEED)
            store.setAnomalies(MOCK_ANOMALIES)
            store.setChangelog(MOCK_CHANGELOG)
            store.setWorkOrders(ALL_MOCK_WORK_ORDERS)
            store.setActivityEntries(MOCK_ACTIVITY_ENTRIES)
            store.setDiscussionComments(MOCK_DISCUSSION)
            store.setExecutionChecklists([MOCK_EXECUTION_CHECKLIST])
            store.setAIRecommendations([MOCK_AI_RECOMMENDATION])
            store.setCurrentUser(MOCK_TEAM[0]) // Default: Sarah Chen
        }
    }, [store])

    const stats = useMemo(() => ({
        totalFactories: MOCK_FACTORIES.length,
        totalWorkflows: MOCK_REPOS.length,
        totalPosts: MOCK_FEED.length,
        pendingAnomalies: MOCK_ANOMALIES.filter(a => a.status === 'pending').length,
        totalWorkOrders: ALL_MOCK_WORK_ORDERS.length,
        totalTeamMembers: MOCK_TEAM.length,
    }), [])

    return { stats, isInitialized: store.factories.length > 0 }
}
