import type { Workflow, VoiceWorkflowIntent } from '@/lib/types/workflow'

// ─── Sample Workflow: Vibration Diagnosis ────────────────────────
export const MOCK_WORKFLOW_VIBRATION: Workflow = {
  id: 'wf_demo_vibration_001',
  title: 'Vibration Diagnosis — Bosch Pump',
  description: 'When a Bosch pump sounds like gravel, diagnose air in the system and create a maintenance ticket.',
  authorId: 'user_carlos_eng',
  createdAt: '2026-02-01T10:00:00.000Z',
  updatedAt: '2026-02-09T08:30:00.000Z',
  version: 3,
  isPublic: false,
  status: 'active',
  targetAsset: {
    type: 'pump',
    brand: 'Bosch',
    model: 'Rexroth A10V',
    tags: ['hydraulic', 'pump', 'vibration'],
  },
  safetyCheck: {
    requiresLoto: true,
    ppeRequired: ['gloves', 'glasses', 'hearing_protection'],
    safetyWarning: 'Ensure pump is depressurized before physical inspection.',
  },
  nodes: [
    {
      id: 'node_1',
      type: 'voice_trigger',
      label: 'Trigger: "vibration, gravel sound"',
      config: { keywords: ['vibración', 'grava', 'vibration', 'gravel'] },
      position: { x: 300, y: 60 },
    },
    {
      id: 'node_2',
      type: 'decision',
      label: 'Vibration on coupling side?',
      config: { condition: 'vibration_location == coupling_side', trueLabel: 'Yes', falseLabel: 'No' },
      position: { x: 300, y: 200 },
    },
    {
      id: 'node_3',
      type: 'log_entry',
      label: 'Log: Alignment Issue Detected',
      config: { message: 'Alignment issue detected on coupling side. Check elastic coupling.' },
      position: { x: 80, y: 360 },
    },
    {
      id: 'node_4',
      type: 'create_ticket',
      label: 'Create Ticket: Bearing Failure',
      config: {
        service: 'jira',
        titleTemplate: 'Bearing Failure — {{asset.brand}} {{asset.model}}',
        descriptionTemplate: 'Auto-generated by OpsFlow. Gravel sound detected, air purge required.',
        priority: 'high',
      },
      position: { x: 520, y: 360 },
    },
    {
      id: 'node_5',
      type: 'send_alert',
      label: 'Alert: Supervisor via Slack',
      config: {
        channel: 'slack',
        recipient: '#maintenance-urgent',
        messageTemplate: 'Bearing failure detected on {{asset.brand}} {{asset.model}}. Ticket created.',
      },
      position: { x: 520, y: 500 },
    },
  ],
  edges: [
    { id: 'edge_1', source: 'node_1', target: 'node_2', animated: true },
    { id: 'edge_2', source: 'node_2', target: 'node_3', sourceHandle: 'true', label: 'Yes' },
    { id: 'edge_3', source: 'node_2', target: 'node_4', sourceHandle: 'false', label: 'No' },
    { id: 'edge_4', source: 'node_4', target: 'node_5', animated: true },
  ],
  tags: ['pump', 'vibration', 'bosch', 'troubleshooting'],
  executionCount: 47,
  lastExecutedAt: '2026-02-08T14:22:00.000Z',
}

// ─── Sample Workflow: Server Rack Inspection ─────────────────────
export const MOCK_WORKFLOW_RACK_INSPECTION: Workflow = {
  id: 'wf_demo_rack_001',
  title: 'Server Rack — Amber Light Response',
  description: 'Quick response workflow when amber PSU light is detected on server rack.',
  authorId: 'user_carlos_eng',
  createdAt: '2026-01-15T08:00:00.000Z',
  updatedAt: '2026-02-05T11:00:00.000Z',
  version: 2,
  isPublic: false,
  status: 'active',
  targetAsset: {
    type: 'server',
    brand: 'Dell',
    model: 'PowerEdge R740',
    tags: ['server', 'datacenter', 'psu'],
  },
  nodes: [
    {
      id: 'rack_1',
      type: 'manual_trigger',
      label: 'Start Inspection',
      config: {},
      position: { x: 300, y: 60 },
    },
    {
      id: 'rack_2',
      type: 'photo_input',
      label: 'Photo: Rack Front Panel',
      config: {},
      position: { x: 300, y: 200 },
    },
    {
      id: 'rack_3',
      type: 'decision',
      label: 'Amber light blinking?',
      config: { condition: 'light_status == amber_blink', trueLabel: 'Blinking', falseLabel: 'Solid' },
      position: { x: 300, y: 340 },
    },
    {
      id: 'rack_4',
      type: 'create_ticket',
      label: 'Ticket: PSU Replacement',
      config: {
        service: 'jira',
        titleTemplate: 'PSU Failure — Rack {{location}}',
        descriptionTemplate: 'Amber blinking PSU detected. Photo attached. Replace PSU.',
        priority: 'critical',
      },
      position: { x: 120, y: 480 },
    },
    {
      id: 'rack_5',
      type: 'log_entry',
      label: 'Log: Monitoring — No Action',
      config: { message: 'Solid amber. Continue monitoring. No immediate action required.' },
      position: { x: 480, y: 480 },
    },
  ],
  edges: [
    { id: 'rack_e1', source: 'rack_1', target: 'rack_2', animated: true },
    { id: 'rack_e2', source: 'rack_2', target: 'rack_3', animated: true },
    { id: 'rack_e3', source: 'rack_3', target: 'rack_4', sourceHandle: 'true', label: 'Blinking' },
    { id: 'rack_e4', source: 'rack_3', target: 'rack_5', sourceHandle: 'false', label: 'Solid' },
  ],
  tags: ['server', 'datacenter', 'dell', 'psu', 'inspection'],
  executionCount: 12,
  lastExecutedAt: '2026-02-07T09:45:00.000Z',
}

// ─── Sample Voice Intent (what AI returns from speech) ───────────
export const MOCK_VOICE_INTENT: VoiceWorkflowIntent = {
  title: 'HVAC Compressor — High Temperature Alert',
  description: 'When HVAC compressor temperature rises abnormally, alert the maintenance team and log the event.',
  targetAsset: {
    type: 'hvac_compressor',
    brand: 'Carrier',
    model: '30XA',
    tags: ['hvac', 'cooling', 'compressor'],
  },
  trigger: {
    type: 'voice_trigger',
    keywords: ['temperature', 'hot', 'overheating', 'compressor'],
  },
  steps: [
    {
      type: 'number_input',
      label: 'Enter current temperature reading',
      config: {},
    },
    {
      type: 'decision',
      label: 'Temperature above 85°C?',
      config: { condition: 'temperature > 85', trueLabel: 'Critical', falseLabel: 'Monitor' },
    },
    {
      type: 'send_alert',
      label: 'Alert: HVAC Team — Critical Temp',
      config: {
        channel: 'slack',
        recipient: '#hvac-alerts',
        messageTemplate: 'Compressor {{asset.model}} at {{temperature}}°C. Immediate inspection required.',
      },
    },
    {
      type: 'create_ticket',
      label: 'Ticket: Compressor Overheating',
      config: {
        service: 'jira',
        titleTemplate: 'CRITICAL: {{asset.brand}} {{asset.model}} Overheating',
        descriptionTemplate: 'Temperature reading: {{temperature}}°C. Auto-generated by OpsFlow.',
        priority: 'critical',
      },
    },
    {
      type: 'log_entry',
      label: 'Log: Temperature Event',
      config: { message: 'Temperature event logged. Workflow executed successfully.' },
    },
  ],
  safetyCheck: {
    requiresLoto: false,
    ppeRequired: ['gloves'],
  },
}

// ─── All mock workflows ──────────────────────────────────────────
export const MOCK_WORKFLOWS: Workflow[] = [
  MOCK_WORKFLOW_VIBRATION,
  MOCK_WORKFLOW_RACK_INSPECTION,
]

// ─── Hook for playground use ─────────────────────────────────────
export function useWorkflowMockData() {
  return {
    workflows: MOCK_WORKFLOWS,
    sampleIntent: MOCK_VOICE_INTENT,
    vibrationWorkflow: MOCK_WORKFLOW_VIBRATION,
    rackWorkflow: MOCK_WORKFLOW_RACK_INSPECTION,
  }
}
